server:
  port: 8080

springdoc:
  swagger-ui:
    path: /
  api-docs:
    path: /api-docs

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health

logging:
  level:
    org.springframework:
      web: DEBUG
      http.converter.json: TRACE
      web.client.RestTemplate: DEBUG

spring:
  profiles:
    active: default


