server:
  port: 8080

springdoc:
  swagger-ui.pat: =/
  api-docs:
    path: /api-docs

management:
  endpoints:
    web:
      exposure:
        includ: health
    health:
      show-details: always

logging:
  level.org:
    springframework:
      web: DEBUG
      http:
        converter: 
          json: TRACE
      web: 
        client:
          RestTemplate: DEBUG

spring:
  profiles:
    active: default

service:
  tableProductService: 
    enabled: false
  mongoProductService:
    enabled: true
  inMemoryProductService:
    enabled: false

product:
  service:
    qualifier: MongoProductService

