server:
  port: 8080

springdoc:
  swagger-ui:
    path: /
  api-docs:
    path: /api-docs

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health

logging:
  level:
    org.springframework:
      web: DEBUG
      http.converter.json: TRACE
      web.client.RestTemplate: DEBUG
    # Add these for more insight into MongoDB auto-configuration and driver activity
    boot.autoconfigure.mongo: DEBUG
  com.mongodb.client: DEBUG

spring:
  profiles:
    active: default
  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@192.168.10.43:27017/techtwist?authSource=admin
      # Remove or update the database property to match the correct case if needed
      database: techtwist
