apiVersion: v1
kind: PersistentVolume
metadata:
  name: external-nfs-pv
  labels:
    usage: external-nfs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/data/k3      # <-- Update this to your exported NFS path
    server: lab-master # <-- Update this to your NFS server's address
  persistentVolumeReclaimPolicy: Retain