name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Build the Docker image
      run: docker build ./Product --file ./Product/Dockerfile --tag ${{ env.IMAGE_TAG }}

    - name: Log in to Docker Hub 
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push the Docker image for x86
      run: docker push ${{ env.IMAGE_TAG }}

    - name: Build and push image for Raspberry Pi (ARM)
      uses: docker/build-push-action@v5
      with:
        context: ./Product
        push: true
        tags: ${{ secrets.DOCKER_REGISTRY }}/product:raspberry-pi
        platforms: linux/arm64

    - name: Build and push image for Intel-based computers (AMD)
      uses: docker/build-push-action@v5
      with:
        context: ./Product
        push: true
        tags: ${{ secrets.DOCKER_REGISTRY }}/product:intel
        platforms: linux/amd64

    - name: Log out from Docker Hub
      run: docker logout

